<a href="https://colab.research.google.com/github/purple1027/AI/blob/%2Bpython/6_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy #넘파이 설치

In [17]:
import numpy as np #임포트
a=np.array(0) #스칼라
print(a)
print(a.ndim) #0차원

a2=np.array([1,2,3,4]) #벡터
print(a2)
print(a2.ndim) #1차원


a3=np.array([[1,2,3],[4,5,6],[7,8,9]]) #행렬 3행 3열
print(a3)
print(a3.ndim) #2차원


a4=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[10,11]]]) #텐서
print(a4)
print(a4.shape)
#3면 2행 2열

a5=np.array([[[1,2],[3,4]],[[5,6],[7,8],],[[9,10],[11,12],]])
print(a5)
print(a5.shape)




0
0
[1 2 3 4]
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [10 11]]]
(2, 3, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [34]:
#reshaping

b=np.arange(12)
print(b)

b.shape
print(b.size,'~~~~')
b.shape=2,-1
print(b)
b.shape

b.shape=3,-1
print(b)

b.shape

b.shape=-1,1

print(b)
b.shape

b.shape=-1,3
print(b)
b.shape

b.shape=-1
print(b)

print(b.size,'~~~~')

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12 ~~~~
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
12 ~~~~


In [32]:
b=np.arange(13)
print(b)

b.shape
#b.shape=2,-1
print(b)
b.shape


[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


(13,)

- 자료형
  - int형 (정수)
    - int64, int8, unint64
  - float형 (실수)
    - float64,32,16
    - 실수의 기본은 float64이다!

  - complex형 (복소수)
    - complex128, 64

In [52]:
#int 자료 표현의 범위

a=np.array([1,3,5,7,9], np.int8)
print(a)
a.dtype

a1=np.array([2147483646,2147483647,2147483649], np.int64)
print(a1)

a2=np.array([2**63, 2**63+1,2**63+2], np.uint64)
print(a2)
a2.dtype


a3=np.array([2**62,-2**62])
print(a3)
a3.dtype


a4=np.array([1,3,5,7,9])
print(a4)
a4.dtype

#결론 자료형을 명하지 않으면 정수형의 기본은 int64
#너무 큰 자료형이므로 메모리절약을 위해서 int8, int16, int32로 바꿀 수 있다!




[1 3 5 7 9]
[2147483646 2147483647 2147483649]
[9223372036854775808 9223372036854775809 9223372036854775810]
[ 4611686018427387904 -4611686018427387904]
[1 3 5 7 9]


dtype('int64')

In [62]:
#실수형

a=np.array(3.141502653589793, np.float64)
print(a)
a.dtype



a2=np.array(3.141502653589793)
print(a2)
a2.dtype


3.141502653589793
3.141502653589793


dtype('float64')

In [73]:
#복소수

a=np.array([1,2j,3+4j,2.72+3.14j])
print(a)
a.dtype
a.real #실수만 추출

a.imag

print(a.real.dtype,'!!')
print(a.imag.dtype,'~~')

[1.  +0.j   0.  +2.j   3.  +4.j   2.72+3.14j]
float64 !!
float64 ~~


1. 인덱싱
  1. 1DArray
  2. 2DArray

2. 슬라이싱
  1. 1DArray
  2. 2DArray

3. iterating
  1. 1DArray
  2. 2DArray

In [82]:
# 1. 인덱싱 1. 1DArray

a=np.array([1,3,5,7,9])
print(a)
print(a.ndim)
print(a.shape)
print(a[0])
print(a[3])
print(a[4])
print(a[-1])
print(a[-2])

[1 3 5 7 9]
1
(5,)
1
7
9
9
7


In [101]:
# 1. 인덱싱 2. 2DArray

a2=np.array([ [1,3,5],[2,4,6] ])
print(a2)
print(a2.ndim)
print(a2.shape)

# 1, 5, 4 추출하기
print(a2[0,0], a2[0,2], a2[1,1])

# 6,3 추출하기
print(a2[1,2], a2[0,1])

# 3자리에 13으로 바꾸기
# 2값을 25로 바꾸기


a2[0,1]=13
a2[1,0]=25

print(a2)


# 0번행 전체의 값에 다가 +10

a2[0]=a2[0]+10
print(a2[0])


#1번 행에 2를 전부 곱하기

a2[1]=a2[1]*2


#1번 열에 2를 전부 나누기

a2[:,1:2]=a2[:,1:2]/2

print(a2)





[[1 3 5]
 [2 4 6]]
2
(2, 3)
1 5 4
6 3
[[ 1 13  5]
 [25  4  6]]
[11 23 15]
[[11 11 15]
 [50  4 12]]


In [143]:
# 슬라이싱
a=np.array([1,3,5,7,9])
print(a)
print(a.ndim)
print(a.shape)
print(a[:])
print(a[0:])
print(a[1:])
print(a[2:])
print(a[3:])
print(a[:0])
print(a[:1])
print(a[:2])
#print(a[1,3,5])

print(a[:-1])
print(a[:-2])

print(a[1:4])

a2=np.arange(10) # 0~9 까지 연속적인 수의 배열 만들기..
print(a2)
print(a2[::2])
print(a2[::3])
print(a2[::-1])
print(a2[1::2])
print(a2[:-2:2])
print(a2[:-4:2])
print(a2[2:-2:2])

a3=np.arange(15)
# 1,3,5,7,9 출력하기

print(a3[1:10:2])

# 2,4,6,8,10,12 출력하기
print(a3[2:13:2])

# 14,13,12,11,10 출력하기
print(a3[-1:9:-1])

#전부 출력하기
print(a3)

# 1열 전부 다 출력하기 [1]
print(a3[1:2])

# 맨마지막 열만 출력하기 [14]

print(a3[-1:-2:-1])

[1 3 5 7 9]
1
(5,)
[1 3 5 7 9]
[1 3 5 7 9]
[3 5 7 9]
[5 7 9]
[7 9]
[]
[1]
[1 3]
[1 3 5 7]
[1 3 5]
[3 5 7]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[9 8 7 6 5 4 3 2 1 0]
[1 3 5 7 9]
[0 2 4 6]
[0 2 4]
[2 4 6]
[1 3 5 7 9]
[ 2  4  6  8 10 12]
[14 13 12 11 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1]
[14]


In [161]:
# 슬라이싱 2D Array
a=np.arange(10,25). reshape(3,5)
print(a)
print(a.shape)

#16 17
#21 22

print(a[1:,1:3])

print(a[ :,3:])


#0~100까지 9행 10열 2차원 배열을 만드세요

a=np.arange(10,100). reshape(9,10)
print(a)

#

print(a[1:5, -4:-1])



[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(3, 5)
[[16 17]
 [21 22]]
[[13 14]
 [18 19]
 [23 24]]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[26 27 28]
 [36 37 38]
 [46 47 48]
 [56 57 58]]


In [169]:
# 3. 이터레이팅 (1)  1D Array

a=np.arange(11)**3
print(a)

for a1 in a:
  print(a1)




[   0    1    8   27   64  125  216  343  512  729 1000]
0
1
8
27
64
125
216
343
512
729
1000


In [176]:
# 3. 이터레이팅 (1)  2D Array
b=np.arange(10,22). reshape(3,4)
#print(b)

for b1 in b:
  print(b1)

#요소별로 출력하기


for b1 in b:
   for b2 in b1:
      print(b2)

[10 11 12 13]
[14 15 16 17]
[18 19 20 21]
10
11
12
13
14
15
16
17
18
19
20
21


# 배열의 명령어 Array Operations

arange
linespace
transpose
reshape
r_
c_
concatenate
hstack, vstack
zeros
ones
full
empty


In [189]:
#arange
a=np.arange(10,101,5)
print(a)

a=np.arange(10, dtype=np.float32)
print(a)

# 0. 0.1 0.2  . . . 0.9
a=np.arange(0,1,0.1)
print(a)
print(a.dtype)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
float64


In [196]:
#linespace

a=np.linespace(0,1,5)
print(a)

AttributeError: module 'numpy' has no attribute 'linespace'

In [204]:
#transpose

a=np.array([[1,2,3],[4,5,6]])
b=a.T #열을 행으로 바꿀 것!

print(a)
print(b)
b2=np.transpose(a) #열을 행으로 바꾼것!
print(b2)

bb2=np.transpose(b2)
print(bb2)

aa=b.T
print(aa)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [209]:
#reshape 행렬의 모양을 바꾸는 것!

a=np.array([1,2,3,4,5,6]).reshape(6,1)
print(a)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [211]:
# r_ row행

a=np.array([1,2,3])
b=np.array([4,5,6,7])

print(a)
print(b)

c=np.r_[a,b]
print(c)

[1 2 3]
[4 5 6 7]
[1 2 3 4 5 6 7]


In [214]:
# C_ 열

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a)
print(b)

c1=np.c_[a,b]
print(c1)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [224]:
# concatenate

a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.concatenate([a,b])
print(c)



[1 2 3 4 5 6]


In [229]:
# concatenate

a=np.array(  [[1,2],[3,4]]  )
b=np.array(  [[5,6],[7,8]]  )
print(a)
print(b)


c=np.concatenate((a,b))
print(c)

c=np.concatenate((a,b),axis=0) #행으로 합치기
print(c)

c=np.concatenate((a,b),axis=1) #열로 합치기
print(c)


c=np.r_[a,b]  #행으로 합치기
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [232]:
#hstack- 수평, vstack - 수직

a=np.array(  [[1,2],[3,4]]  )
b=np.array(  [[5,6],[7,8]]  )

c=np.hstack((a,b))
print(c)

c1=np.vstack((a,b))
print(c1)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [242]:
# zeros, ones, full, empty


a=np.zeros(5)
print(a)

a=np.ones(5)
print(a)

a2=np.zeros((3,5))
print(a2)


a3=np.ones((5,4))
print(a3)

print(a.dtype)
print(a.ndim)

# 모든요소 값을 전부 5로 하고 싶다

a=np.full(10,5) #10열 5 값을 전부 넣기
print(a)

a1=np.full((3,4),7)
print(a1)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
1
[5 5 5 5 5 5 5 5 5 5]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [250]:
# empty 항목을 초기화하지 않고 주어진 모양과 유형의 새 배열을 반환
a = np.empty(4)
print( a )
a = np.empty(4, dtype=np.int64)
print( a )
a = np.empty( (2,4), dtype=np.int32 )
print( a )

[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
[1 2 3 4]
[[1 0 2 0]
 [3 0 4 0]]


### 수학 명령어 Math Operation
- Braodcasting - + * / % ** <배열연산>
- Matrix Multiplication 행렬곱
- 제곱근, 제곱합
- 합계
- 누적합계
- 평균



In [254]:
#Braodcasting - + * / % **  배열연산


a=np.array([ [1,2,3],[4,5,6]] )
b=np.array([ [2,2,2],[3,3,3]] )

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)


[[3 4 5]
 [7 8 9]]
[[-1  0  1]
 [ 1  2  3]]
[[ 2  4  6]
 [12 15 18]]
[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]
[[1 0 1]
 [1 2 0]]
[[  1   4   9]
 [ 64 125 216]]


In [257]:
# Matrix Multiplication 행렬곱


a=np.array([ [1,2,3],[4,5,6]] )
b=np.array([ [2,2],[3,3],[4,4]] )


c=a@b
print( c )

c=np.matmul(a,b)
print( c )

[[20 20]
 [47 47]]
[[20 20]
 [47 47]]


In [274]:
# 제곱

a=np.array([1,2,3,4])
a1=np.square(a)
print(a1)

a=np.array([1,2,3,4])
print(np.sqrt(a))

# 합계

print(np.sum(a))

#평균
print(np.average(a))
print(np.mean(a))

#최대값
print(np.max(a))

#최소값

print(np.min(a))


#누적합

a=np.array([1,2,3,4,5])
print(np.cumsum(a))

#누적곱
a=np.arange(1,7)
print(a)
print(np.cumprod(a))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
10
2.5
2.5
4
1
[ 1  3  6 10 15]
[1 2 3 4 5 6]
[  1   2   6  24 120 720]


파이

- e
- exp
- sin
- cos
- tan
- log

In [281]:
from numpy import pi, e
print(pi)
print(e)




3.141592653589793
2.718281828459045


In [284]:
import numpy as np

np.exp(1)
x=np.array([0,1,2])
y=np.exp(x)
print(y)

[1.         2.71828183 7.3890561 ]


In [292]:
import matplotlib.pyplot as pit #지수 함수로 그래프 그리기

y=np.linspace(-2,2,100)
print(y)


y=np.exp(y)
print(y)

plt.plot(x,y)
plt.show()


[-2.         -1.95959596 -1.91919192 -1.87878788 -1.83838384 -1.7979798
 -1.75757576 -1.71717172 -1.67676768 -1.63636364 -1.5959596  -1.55555556
 -1.51515152 -1.47474747 -1.43434343 -1.39393939 -1.35353535 -1.31313131
 -1.27272727 -1.23232323 -1.19191919 -1.15151515 -1.11111111 -1.07070707
 -1.03030303 -0.98989899 -0.94949495 -0.90909091 -0.86868687 -0.82828283
 -0.78787879 -0.74747475 -0.70707071 -0.66666667 -0.62626263 -0.58585859
 -0.54545455 -0.50505051 -0.46464646 -0.42424242 -0.38383838 -0.34343434
 -0.3030303  -0.26262626 -0.22222222 -0.18181818 -0.14141414 -0.1010101
 -0.06060606 -0.02020202  0.02020202  0.06060606  0.1010101   0.14141414
  0.18181818  0.22222222  0.26262626  0.3030303   0.34343434  0.38383838
  0.42424242  0.46464646  0.50505051  0.54545455  0.58585859  0.62626263
  0.66666667  0.70707071  0.74747475  0.78787879  0.82828283  0.86868687
  0.90909091  0.94949495  0.98989899  1.03030303  1.07070707  1.11111111
  1.15151515  1.19191919  1.23232323  1.27272727  1.3

NameError: name 'plt' is not defined

random-난수

In [296]:
np.random.rand()

print(np.random.rand(3,5)) #3행 5열짜리 랜덤수 구하기

[[0.42953332 0.75621313 0.40078391 0.812389   0.47345087]
 [0.87254218 0.928999   0.92932393 0.68185505 0.8238089 ]
 [0.33082176 0.78402401 0.3918078  0.54305136 0.17807167]]


- 파일로 저장하기
- 파일로 불러오기


In [301]:
# 0~99까지  10행 10열 2차원 배열 만들기
a=np.arange(0,100). reshape(10,10)
print(a)

np.save('test.npy',a)



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [302]:
# 넌파이 불러오기
k=np.load('test.npy')

print(k)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# 우수 초콜릿 분석 하기

In [304]:
from google.colab import files
f = files.upload() # 파일 업로드하기

Saving chocolate_rating.csv to chocolate_rating.csv


In [316]:


print(data)

print(data.ndim)

print(data.shape)

print(data.size)



[[1.000e+00 2.016e+03 6.300e-01 3.750e+00]
 [2.000e+00 2.015e+03 7.000e-01 2.750e+00]
 [3.000e+00 2.015e+03 7.000e-01 3.000e+00]
 ...
 [1.793e+03 2.011e+03 6.500e-01 3.500e+00]
 [1.794e+03 2.011e+03 6.200e-01 3.250e+00]
 [1.795e+03 2.010e+03 6.500e-01 3.000e+00]]
2
(1795, 4)
7180


In [332]:
rating_mean=data[:,3].mean()
print(rating_mean)

high_level=data[data[:,3]>=4]
#print(high_level[0:10])
high_id=high_level[:,0].astype(np.int64)
print(high_id)

print('우수 초콜릿 수는?',high_id.size)

3.185933147632312
[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]
우수 초콜릿 수는? 100


In [343]:
high_kakao=high_level[:,2]
print(high_kakao)

unique_values,value_counts=np.unique(high_kakao, return_counts=True)
print('카카오함유량:',unique_values)
print('함유량별 빈도수:',value_counts)

[0.7  0.7  0.63 0.7  0.7  0.7  0.75 0.7  0.7  0.7  0.66 0.6  0.7  0.7
 0.7  0.72 0.7  0.73 0.72 0.72 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75
 0.7  0.71 0.7  0.7  0.72 0.75 0.7  0.7  0.7  0.7  0.7  0.7  0.68 0.7
 0.74 0.69 0.7  0.74 0.7  0.72 0.7  0.74 0.7  0.72 0.72 0.7  0.7  0.63
 0.68 0.74 0.67 0.65 0.64 0.75 0.7  0.7  0.7  0.75 0.7  0.67 0.7  0.72
 0.72 0.72 0.75 0.75 0.8  0.75 0.75 0.7  0.78 0.65 0.7  0.72 0.7  0.75
 0.88 0.7  0.67 0.7  0.7  0.7  0.64 0.7  0.7  0.63 0.69 0.64 0.64 0.7
 0.7  0.7 ]
카카오함유량: [0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]
함유량별 빈도수: [ 1  3  4  2  1  3  2  2 45  1 11  1  4 17  1  1  1]


In [351]:
max_idx=np.argmax(value_counts)
print(max_idx)

print(unique_values[max_idx])

print( '우수초콜릿', high_id.size, '가지 중', value_counts[ max_idx], '가지의 카카오 함유량이 ', unique_values[ max_idx ] * 100, '%입니다'  )



8
0.7
우수초콜릿 100 가지 중 45 가지의 카카오 함유량이  70.0 %입니다
